// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "path";
import { config as loadEnv } from "dotenv";
import { defineConfig } from "@prisma/config";

loadEnv({ path: path.resolve(__dirname, ".env") });

export default defineConfig({
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
